server:
  port: 8080

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health

spring:
  application:
    name: Youtube Tunnel Application

config:
  key: ${YOUTUBE_API_KEY:key}
cors:
  cors-list:
    - http://localhost:5173
