server:
  port: 8080

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health

spring:
  application:
    name: Youtube Tunnel Application
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-fcog2dztfmr14aao.us.auth0.com/
          audiences:
          - http://localhost:8080

config:
  key: ${YOUTUBE_API_KEY:key}
  host: ${YOUTUBE_BASE_HOST:https://www.googleapis.com}
cors:
  cors-list:
    - http://localhost:5173
