server:
  port: 8080

spring:
  application:
    name: Youtube Tunnel Main Service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
config:
  key: ${YOUTUBE_API_KEY:key}
  host: ${YOUTUBE_BASE_HOST:https://www.googleapis.com}

minio:
  externalUrl: ${MINIO_EXTERNAL_URL:http://localhost:1111}
  username: ${MINIO_USERNAME:user}
  password: ${MINIO_PASSWORD:password}
cors:
  cors-list:
    - http://localhost:5173

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
