version: '3.8'

services:
  api:
    image: youtube-tunnel-api:latest
    container_name: yt-api
    networks:
      - yt-network
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      YOUTUBE_API_KEY: test
      YOUTUBE_HOST: https://www.googleapis.com
      REDIS_HOST: yt-redis
      REDIS_PORT: "6379"
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      AWS_REGION: us-east-1
      MINIO_ENDPOINT: http://minio:9000
    expose:
      - "8080"

  worker:
    image: youtube-tunnel-worker:latest
    container_name: worker
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8081
      REDIS_HOST: yt-redis
      REDIS_PORT: "6379"
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      AWS_REGION: us-east-1
      MINIO_ENDPOINT: http://minio:9000
    networks:
      - yt-network
    expose:
      - "8081"

  web:
    image: youtube-tunnel-web:latest
    container_name: yt-web
    networks:
      - yt-network
    expose:
      - "80"

networks:
  yt-network:
    external: true
  proxy:
    external: true
