server:
  port: 8081

spring:
  application:
    name: Youtube Tunnel Worker Service
  data:
    redis:
      host: ${REDIS_HOST:yt-redis}
      port: ${REDIS_PORT:6379}

minio:
  internalUrl: ${MINIO_INTERNAL_URL:http://localhost:1111}
  username: ${MINIO_USERNAME:user}
  password: ${MINIO_PASSWORD:password}
