[package]
name = "service"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }

anyhow.workspace = true
aws-sdk-s3.workspace = true

# Logger
tracing.workspace = true

# Redis pool
deadpool-redis.workspace = true
tokio.workspace = true
serde_json.workspace = true